### ISSUE TITLE
Changing a topic doesn't mark a game as dirty

### ISSUE THREAD

**Issue by Rodigee** [steve-mcclellan/j-scorer#67]
- Open up a previously saved game
- Change the topics for a category

Result: The game isn't marked as dirty so the option to save the game doesn't appear. 

A workaround is to change a clue's response state and then change it back. Then the option to save the game appears.

**Comment by steve-mcclellan** [comment]
Thanks for the report.

The behavior I'm seeing is that a change in topics is detected when the Topic(s) box loses focus. So, just tabbing/clicking/tapping out of the box enables the save link. (On my computer, clicking on the disabled save link both enables it and immediately registers the click, saving the game.)

If that's the case for you as well, this is a low priority issue, and I'll get around to it sometime.

If something different is happening for you, please let me know what OS and browser you're using, so I can see about reproducing it.

**Comment by Rodigee** [comment]
You're right, I just wasn't tabbing out of the topic box. I don't think this is worth fixing.
